### ISSUE TITLE
Question: Implementation of unit test

### ISSUE THREAD

**Issue by icardenas** [PandaDoc/pandadoc-api-python-client#19]
Hi team! 

I like to propose to my team the use of this lib, but I don't see any related to unit tests for this library. I like to confirm with you that you are controlling their quality and the tests were excluded from this GitHub project for some reason. In this way, we can rely on that the code to be implemented is correct and we will not encounter any blockers. 

Thank you!

**Comment by amelishko** [comment]
Hello Iván,

There are no tests but the package was thoroughly tested manually.

Thanks!
Mick
